openapi: 3.0.3

info:
  title: Coffee Order API
  version: 1.0.0
  description: |
    Verwaltung von Kaffeebestellungen.
    Jede Kaffeebestellung referenziert das bestellte Kaffeeprodukt (vom coffee-menu-service)
    und optional die Zutaten (vom coffee-ingredient-service).

servers:
  - url: http://coffee-order-service:8080

security:
  - bearerAuth: [ ]

tags:
  - name: Order

paths:

  /orders:
    get:
      summary: Liste aller Kaffeebestellungen
      operationId: listOrders
      tags: [ Order ]
      responses:
        '200':
          description: Liste mit Kaffeebestellungen
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderCollection'
    post:
      summary: Neue Kaffeebestellung erstellen
      operationId: createOrder
      tags: [ Order ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewOrder'
      responses:
        '201':
          description: Bestellung erstellt
          headers:
            Location:
              description: URI der neuen Bestellung
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

  /orders/{orderId}:
    get:
      summary: Einzelne Kaffeebestellung abrufen
      operationId: getOrder
      tags: [ Order ]
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Eine Kaffeebestellung
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

    delete:
      summary: Kaffeebestellung löschen
      operationId: deleteOrder
      tags: [ CoffeeOrder ]
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Kaffeebestellung gelöscht

components:

  securitySchemes:

    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    NewOrder:
      type: object
      required: [ coffeeType, userId ]
      properties:
        coffeeType:
          type: string
          example: espresso
        userId:
          type: string
          example: u123

    Order:
      type: object
      required: [ id, coffeeType, totalPrice, status, userId ]
      properties:
        id:
          type: string
          example: 42
        coffeeType:
          type: string
          description: Bestelltes Kaffeeprodukt
          example: espresso
        ingredients:
          type: array
          description: Zutaten-Link für das Kaffeeprodukt
          items:
            type: string
        totalPrice:
          type: number
          description: Gesamtpreis der Bestellung
        status:
          type: string
          description: Bestellstatus
          enum: [ created, completed, cancelled ]
        userId:
          type: string
          example: u123

    OrderCollection:
      type: array
      items:
        $ref: '#/components/schemas/Order'

